### ISSUE TITLE
uname 2.6 personality

### ISSUE THREAD

**Issue by glensc** [linux-vserver/util-vserver#23]
can we get support of adding [personality to report 2.6.x version numbers](https://lwn.net/Articles/451168/)

from current code (assuming i look right place) it is not yet supported: https://github.com/linux-vserver/util-vserver/blob/master/lib/personalitytype.c#L34-L119

**Comment by dhozac** [comment]
Although you could already do this using /etc/vservers/<guest>/uts/release, where you can set it to report whatever you want.
