### ISSUE TITLE
Users have no way to find out when a process started

### ISSUE THREAD

**Issue by jidanni** [linux-vserver/util-vserver#27]
User does ps aux to find out if he has any processes lying around from
yesterday that are stuck etc.

User sees erroneous start dates months off for all processes.

User has absolutely no way to find out when a process started.

See http://bugs.debian.org/842879 .

**Comment by dhozac** [comment]
This would be a problem in the kernel, not in util-vserver. Please contact the vserver mailing list instead.

**Comment by jidanni** [comment]
OK I posted http://list.linux-vserver.org/archive?mss:7091 .
