### ISSUE TITLE
Network interface if/up

### ISSUE THREAD

**Issue by MartusDortus** [linux-vserver/util-vserver#28]
Hello,

We are running X VServer and proxy VServer on one physical machine.

I need network 192.168.1.0/24 on both Xserver and proxy server  set up, so on X I'm setting 192.168.1.12/24 and on proxy I'm setting 192.168.1.14/24 (both are 255.255.255.0 networks).

Here comes the issue - when I stop proxy vserver (.14/24) it also shut down X networks down (.12/24), and then I've to stop/start the X server, to set interfaces UP.

Is there any way to set the VServer ifaces without stop/starting it? 

Thanks for reply.

Have a nice day
Martin Kusnier

**Comment by dhozac** [comment]
You should just enable promote_secondaries on your interfaces, or give the host one of them, to ensure that the address isn't removed when stopping whichever guest happened to start first. Also, questions like these are probably better suited for the mailing list.
